//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace YQCMS.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class CmsEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“CmsEntities”部分中的连接字符串初始化新 CmsEntities 对象。
        /// </summary>
        public CmsEntities() : base("name=CmsEntities", "CmsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 CmsEntities 对象。
        /// </summary>
        public CmsEntities(string connectionString) : base(connectionString, "CmsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 CmsEntities 对象。
        /// </summary>
        public CmsEntities(EntityConnection connection) : base(connection, "CmsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<cms_article> cms_article
        {
            get
            {
                if ((_cms_article == null))
                {
                    _cms_article = base.CreateObjectSet<cms_article>("cms_article");
                }
                return _cms_article;
            }
        }
        private ObjectSet<cms_article> _cms_article;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<cms_varticle> cms_varticle
        {
            get
            {
                if ((_cms_varticle == null))
                {
                    _cms_varticle = base.CreateObjectSet<cms_varticle>("cms_varticle");
                }
                return _cms_varticle;
            }
        }
        private ObjectSet<cms_varticle> _cms_varticle;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<cms_articledetail> cms_articledetail
        {
            get
            {
                if ((_cms_articledetail == null))
                {
                    _cms_articledetail = base.CreateObjectSet<cms_articledetail>("cms_articledetail");
                }
                return _cms_articledetail;
            }
        }
        private ObjectSet<cms_articledetail> _cms_articledetail;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 cms_article EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocms_article(cms_article cms_article)
        {
            base.AddObject("cms_article", cms_article);
        }
    
        /// <summary>
        /// 用于向 cms_varticle EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocms_varticle(cms_varticle cms_varticle)
        {
            base.AddObject("cms_varticle", cms_varticle);
        }
    
        /// <summary>
        /// 用于向 cms_articledetail EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocms_articledetail(cms_articledetail cms_articledetail)
        {
            base.AddObject("cms_articledetail", cms_articledetail);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmsModel", Name="cms_article")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cms_article : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 cms_article 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="cateid">cateid 属性的初始值。</param>
        /// <param name="catepath">catepath 属性的初始值。</param>
        /// <param name="articleid">articleid 属性的初始值。</param>
        /// <param name="parentid">parentid 属性的初始值。</param>
        /// <param name="layer">layer 属性的初始值。</param>
        /// <param name="subcount">subcount 属性的初始值。</param>
        /// <param name="catename">catename 属性的初始值。</param>
        /// <param name="userid">userid 属性的初始值。</param>
        /// <param name="username">username 属性的初始值。</param>
        /// <param name="title">title 属性的初始值。</param>
        /// <param name="summary">summary 属性的初始值。</param>
        /// <param name="content">content 属性的初始值。</param>
        /// <param name="viewcount">viewcount 属性的初始值。</param>
        /// <param name="orderid">orderid 属性的初始值。</param>
        /// <param name="replypermit">replypermit 属性的初始值。</param>
        /// <param name="status">status 属性的初始值。</param>
        /// <param name="ip">ip 属性的初始值。</param>
        /// <param name="createdate">createdate 属性的初始值。</param>
        /// <param name="typeid">typeid 属性的初始值。</param>
        /// <param name="favor">favor 属性的初始值。</param>
        /// <param name="against">against 属性的初始值。</param>
        /// <param name="iscommend">iscommend 属性的初始值。</param>
        /// <param name="istop">istop 属性的初始值。</param>
        /// <param name="lastreplydate">lastreplydate 属性的初始值。</param>
        /// <param name="lastreplyuser">lastreplyuser 属性的初始值。</param>
        public static cms_article Createcms_article(global::System.Int32 id, global::System.Int32 cateid, global::System.String catepath, global::System.Int32 articleid, global::System.Int32 parentid, global::System.Int32 layer, global::System.Int32 subcount, global::System.String catename, global::System.Int32 userid, global::System.String username, global::System.String title, global::System.String summary, global::System.String content, global::System.Int32 viewcount, global::System.Int32 orderid, global::System.Byte replypermit, global::System.Byte status, global::System.String ip, global::System.DateTime createdate, global::System.Int32 typeid, global::System.Int32 favor, global::System.Int32 against, global::System.Byte iscommend, global::System.Byte istop, global::System.DateTime lastreplydate, global::System.String lastreplyuser)
        {
            cms_article cms_article = new cms_article();
            cms_article.id = id;
            cms_article.cateid = cateid;
            cms_article.catepath = catepath;
            cms_article.articleid = articleid;
            cms_article.parentid = parentid;
            cms_article.layer = layer;
            cms_article.subcount = subcount;
            cms_article.catename = catename;
            cms_article.userid = userid;
            cms_article.username = username;
            cms_article.title = title;
            cms_article.summary = summary;
            cms_article.content = content;
            cms_article.viewcount = viewcount;
            cms_article.orderid = orderid;
            cms_article.replypermit = replypermit;
            cms_article.status = status;
            cms_article.ip = ip;
            cms_article.createdate = createdate;
            cms_article.typeid = typeid;
            cms_article.favor = favor;
            cms_article.against = against;
            cms_article.iscommend = iscommend;
            cms_article.istop = istop;
            cms_article.lastreplydate = lastreplydate;
            cms_article.lastreplyuser = lastreplyuser;
            return cms_article;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cateid
        {
            get
            {
                return _cateid;
            }
            set
            {
                OncateidChanging(value);
                ReportPropertyChanging("cateid");
                _cateid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cateid");
                OncateidChanged();
            }
        }
        private global::System.Int32 _cateid;
        partial void OncateidChanging(global::System.Int32 value);
        partial void OncateidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String catepath
        {
            get
            {
                return _catepath;
            }
            set
            {
                OncatepathChanging(value);
                ReportPropertyChanging("catepath");
                _catepath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("catepath");
                OncatepathChanged();
            }
        }
        private global::System.String _catepath;
        partial void OncatepathChanging(global::System.String value);
        partial void OncatepathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 articleid
        {
            get
            {
                return _articleid;
            }
            set
            {
                OnarticleidChanging(value);
                ReportPropertyChanging("articleid");
                _articleid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("articleid");
                OnarticleidChanged();
            }
        }
        private global::System.Int32 _articleid;
        partial void OnarticleidChanging(global::System.Int32 value);
        partial void OnarticleidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentid
        {
            get
            {
                return _parentid;
            }
            set
            {
                OnparentidChanging(value);
                ReportPropertyChanging("parentid");
                _parentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentid");
                OnparentidChanged();
            }
        }
        private global::System.Int32 _parentid;
        partial void OnparentidChanging(global::System.Int32 value);
        partial void OnparentidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 layer
        {
            get
            {
                return _layer;
            }
            set
            {
                OnlayerChanging(value);
                ReportPropertyChanging("layer");
                _layer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("layer");
                OnlayerChanged();
            }
        }
        private global::System.Int32 _layer;
        partial void OnlayerChanging(global::System.Int32 value);
        partial void OnlayerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 subcount
        {
            get
            {
                return _subcount;
            }
            set
            {
                OnsubcountChanging(value);
                ReportPropertyChanging("subcount");
                _subcount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("subcount");
                OnsubcountChanged();
            }
        }
        private global::System.Int32 _subcount;
        partial void OnsubcountChanging(global::System.Int32 value);
        partial void OnsubcountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String catename
        {
            get
            {
                return _catename;
            }
            set
            {
                OncatenameChanging(value);
                ReportPropertyChanging("catename");
                _catename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("catename");
                OncatenameChanged();
            }
        }
        private global::System.String _catename;
        partial void OncatenameChanging(global::System.String value);
        partial void OncatenameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private global::System.Int32 _userid;
        partial void OnuseridChanging(global::System.Int32 value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String summary
        {
            get
            {
                return _summary;
            }
            set
            {
                OnsummaryChanging(value);
                ReportPropertyChanging("summary");
                _summary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("summary");
                OnsummaryChanged();
            }
        }
        private global::System.String _summary;
        partial void OnsummaryChanging(global::System.String value);
        partial void OnsummaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 viewcount
        {
            get
            {
                return _viewcount;
            }
            set
            {
                OnviewcountChanging(value);
                ReportPropertyChanging("viewcount");
                _viewcount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viewcount");
                OnviewcountChanged();
            }
        }
        private global::System.Int32 _viewcount;
        partial void OnviewcountChanging(global::System.Int32 value);
        partial void OnviewcountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderid
        {
            get
            {
                return _orderid;
            }
            set
            {
                OnorderidChanging(value);
                ReportPropertyChanging("orderid");
                _orderid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderid");
                OnorderidChanged();
            }
        }
        private global::System.Int32 _orderid;
        partial void OnorderidChanging(global::System.Int32 value);
        partial void OnorderidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte replypermit
        {
            get
            {
                return _replypermit;
            }
            set
            {
                OnreplypermitChanging(value);
                ReportPropertyChanging("replypermit");
                _replypermit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("replypermit");
                OnreplypermitChanged();
            }
        }
        private global::System.Byte _replypermit;
        partial void OnreplypermitChanging(global::System.Byte value);
        partial void OnreplypermitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Byte _status;
        partial void OnstatusChanging(global::System.Byte value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ip
        {
            get
            {
                return _ip;
            }
            set
            {
                OnipChanging(value);
                ReportPropertyChanging("ip");
                _ip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ip");
                OnipChanged();
            }
        }
        private global::System.String _ip;
        partial void OnipChanging(global::System.String value);
        partial void OnipChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createdate
        {
            get
            {
                return _createdate;
            }
            set
            {
                OncreatedateChanging(value);
                ReportPropertyChanging("createdate");
                _createdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdate");
                OncreatedateChanged();
            }
        }
        private global::System.DateTime _createdate;
        partial void OncreatedateChanging(global::System.DateTime value);
        partial void OncreatedateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 typeid
        {
            get
            {
                return _typeid;
            }
            set
            {
                OntypeidChanging(value);
                ReportPropertyChanging("typeid");
                _typeid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("typeid");
                OntypeidChanged();
            }
        }
        private global::System.Int32 _typeid;
        partial void OntypeidChanging(global::System.Int32 value);
        partial void OntypeidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 favor
        {
            get
            {
                return _favor;
            }
            set
            {
                OnfavorChanging(value);
                ReportPropertyChanging("favor");
                _favor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("favor");
                OnfavorChanged();
            }
        }
        private global::System.Int32 _favor;
        partial void OnfavorChanging(global::System.Int32 value);
        partial void OnfavorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 against
        {
            get
            {
                return _against;
            }
            set
            {
                OnagainstChanging(value);
                ReportPropertyChanging("against");
                _against = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("against");
                OnagainstChanged();
            }
        }
        private global::System.Int32 _against;
        partial void OnagainstChanging(global::System.Int32 value);
        partial void OnagainstChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte iscommend
        {
            get
            {
                return _iscommend;
            }
            set
            {
                OniscommendChanging(value);
                ReportPropertyChanging("iscommend");
                _iscommend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iscommend");
                OniscommendChanged();
            }
        }
        private global::System.Byte _iscommend;
        partial void OniscommendChanging(global::System.Byte value);
        partial void OniscommendChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte istop
        {
            get
            {
                return _istop;
            }
            set
            {
                OnistopChanging(value);
                ReportPropertyChanging("istop");
                _istop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("istop");
                OnistopChanged();
            }
        }
        private global::System.Byte _istop;
        partial void OnistopChanging(global::System.Byte value);
        partial void OnistopChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime lastreplydate
        {
            get
            {
                return _lastreplydate;
            }
            set
            {
                OnlastreplydateChanging(value);
                ReportPropertyChanging("lastreplydate");
                _lastreplydate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastreplydate");
                OnlastreplydateChanged();
            }
        }
        private global::System.DateTime _lastreplydate;
        partial void OnlastreplydateChanging(global::System.DateTime value);
        partial void OnlastreplydateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastreplyuser
        {
            get
            {
                return _lastreplyuser;
            }
            set
            {
                OnlastreplyuserChanging(value);
                ReportPropertyChanging("lastreplyuser");
                _lastreplyuser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastreplyuser");
                OnlastreplyuserChanged();
            }
        }
        private global::System.String _lastreplyuser;
        partial void OnlastreplyuserChanging(global::System.String value);
        partial void OnlastreplyuserChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmsModel", Name="cms_articledetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cms_articledetail : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 cms_articledetail 对象。
        /// </summary>
        /// <param name="articleid">articleid 属性的初始值。</param>
        /// <param name="seotitle">seotitle 属性的初始值。</param>
        /// <param name="seodescription">seodescription 属性的初始值。</param>
        /// <param name="seokeywords">seokeywords 属性的初始值。</param>
        /// <param name="seometas">seometas 属性的初始值。</param>
        /// <param name="rename">rename 属性的初始值。</param>
        /// <param name="tags">tags 属性的初始值。</param>
        public static cms_articledetail Createcms_articledetail(global::System.Int32 articleid, global::System.String seotitle, global::System.String seodescription, global::System.String seokeywords, global::System.String seometas, global::System.String rename, global::System.String tags)
        {
            cms_articledetail cms_articledetail = new cms_articledetail();
            cms_articledetail.articleid = articleid;
            cms_articledetail.seotitle = seotitle;
            cms_articledetail.seodescription = seodescription;
            cms_articledetail.seokeywords = seokeywords;
            cms_articledetail.seometas = seometas;
            cms_articledetail.rename = rename;
            cms_articledetail.tags = tags;
            return cms_articledetail;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 articleid
        {
            get
            {
                return _articleid;
            }
            set
            {
                if (_articleid != value)
                {
                    OnarticleidChanging(value);
                    ReportPropertyChanging("articleid");
                    _articleid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("articleid");
                    OnarticleidChanged();
                }
            }
        }
        private global::System.Int32 _articleid;
        partial void OnarticleidChanging(global::System.Int32 value);
        partial void OnarticleidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String seotitle
        {
            get
            {
                return _seotitle;
            }
            set
            {
                OnseotitleChanging(value);
                ReportPropertyChanging("seotitle");
                _seotitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("seotitle");
                OnseotitleChanged();
            }
        }
        private global::System.String _seotitle;
        partial void OnseotitleChanging(global::System.String value);
        partial void OnseotitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String seodescription
        {
            get
            {
                return _seodescription;
            }
            set
            {
                OnseodescriptionChanging(value);
                ReportPropertyChanging("seodescription");
                _seodescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("seodescription");
                OnseodescriptionChanged();
            }
        }
        private global::System.String _seodescription;
        partial void OnseodescriptionChanging(global::System.String value);
        partial void OnseodescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String seokeywords
        {
            get
            {
                return _seokeywords;
            }
            set
            {
                OnseokeywordsChanging(value);
                ReportPropertyChanging("seokeywords");
                _seokeywords = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("seokeywords");
                OnseokeywordsChanged();
            }
        }
        private global::System.String _seokeywords;
        partial void OnseokeywordsChanging(global::System.String value);
        partial void OnseokeywordsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String seometas
        {
            get
            {
                return _seometas;
            }
            set
            {
                OnseometasChanging(value);
                ReportPropertyChanging("seometas");
                _seometas = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("seometas");
                OnseometasChanged();
            }
        }
        private global::System.String _seometas;
        partial void OnseometasChanging(global::System.String value);
        partial void OnseometasChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rename
        {
            get
            {
                return _rename;
            }
            set
            {
                OnrenameChanging(value);
                ReportPropertyChanging("rename");
                _rename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rename");
                OnrenameChanged();
            }
        }
        private global::System.String _rename;
        partial void OnrenameChanging(global::System.String value);
        partial void OnrenameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tags
        {
            get
            {
                return _tags;
            }
            set
            {
                OntagsChanging(value);
                ReportPropertyChanging("tags");
                _tags = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tags");
                OntagsChanged();
            }
        }
        private global::System.String _tags;
        partial void OntagsChanging(global::System.String value);
        partial void OntagsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CmsModel", Name="cms_varticle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cms_varticle : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 cms_varticle 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="cateid">cateid 属性的初始值。</param>
        /// <param name="catepath">catepath 属性的初始值。</param>
        /// <param name="articleid">articleid 属性的初始值。</param>
        /// <param name="parentid">parentid 属性的初始值。</param>
        /// <param name="layer">layer 属性的初始值。</param>
        /// <param name="subcount">subcount 属性的初始值。</param>
        /// <param name="catename">catename 属性的初始值。</param>
        /// <param name="userid">userid 属性的初始值。</param>
        /// <param name="username">username 属性的初始值。</param>
        /// <param name="title">title 属性的初始值。</param>
        /// <param name="summary">summary 属性的初始值。</param>
        /// <param name="content">content 属性的初始值。</param>
        /// <param name="viewcount">viewcount 属性的初始值。</param>
        /// <param name="orderid">orderid 属性的初始值。</param>
        /// <param name="replypermit">replypermit 属性的初始值。</param>
        /// <param name="status">status 属性的初始值。</param>
        /// <param name="ip">ip 属性的初始值。</param>
        /// <param name="createdate">createdate 属性的初始值。</param>
        /// <param name="seotitle">seotitle 属性的初始值。</param>
        /// <param name="seodescription">seodescription 属性的初始值。</param>
        /// <param name="seokeywords">seokeywords 属性的初始值。</param>
        /// <param name="seometas">seometas 属性的初始值。</param>
        /// <param name="typeid">typeid 属性的初始值。</param>
        /// <param name="favor">favor 属性的初始值。</param>
        /// <param name="against">against 属性的初始值。</param>
        /// <param name="rename">rename 属性的初始值。</param>
        /// <param name="tags">tags 属性的初始值。</param>
        /// <param name="iscommend">iscommend 属性的初始值。</param>
        /// <param name="istop">istop 属性的初始值。</param>
        /// <param name="lastreplydate">lastreplydate 属性的初始值。</param>
        /// <param name="lastreplyuser">lastreplyuser 属性的初始值。</param>
        public static cms_varticle Createcms_varticle(global::System.Int32 id, global::System.Int32 cateid, global::System.String catepath, global::System.Int32 articleid, global::System.Int32 parentid, global::System.Int32 layer, global::System.Int32 subcount, global::System.String catename, global::System.Int32 userid, global::System.String username, global::System.String title, global::System.String summary, global::System.String content, global::System.Int32 viewcount, global::System.Int32 orderid, global::System.Byte replypermit, global::System.Byte status, global::System.String ip, global::System.DateTime createdate, global::System.String seotitle, global::System.String seodescription, global::System.String seokeywords, global::System.String seometas, global::System.Int32 typeid, global::System.Int32 favor, global::System.Int32 against, global::System.String rename, global::System.String tags, global::System.Byte iscommend, global::System.Byte istop, global::System.DateTime lastreplydate, global::System.String lastreplyuser)
        {
            cms_varticle cms_varticle = new cms_varticle();
            cms_varticle.id = id;
            cms_varticle.cateid = cateid;
            cms_varticle.catepath = catepath;
            cms_varticle.articleid = articleid;
            cms_varticle.parentid = parentid;
            cms_varticle.layer = layer;
            cms_varticle.subcount = subcount;
            cms_varticle.catename = catename;
            cms_varticle.userid = userid;
            cms_varticle.username = username;
            cms_varticle.title = title;
            cms_varticle.summary = summary;
            cms_varticle.content = content;
            cms_varticle.viewcount = viewcount;
            cms_varticle.orderid = orderid;
            cms_varticle.replypermit = replypermit;
            cms_varticle.status = status;
            cms_varticle.ip = ip;
            cms_varticle.createdate = createdate;
            cms_varticle.seotitle = seotitle;
            cms_varticle.seodescription = seodescription;
            cms_varticle.seokeywords = seokeywords;
            cms_varticle.seometas = seometas;
            cms_varticle.typeid = typeid;
            cms_varticle.favor = favor;
            cms_varticle.against = against;
            cms_varticle.rename = rename;
            cms_varticle.tags = tags;
            cms_varticle.iscommend = iscommend;
            cms_varticle.istop = istop;
            cms_varticle.lastreplydate = lastreplydate;
            cms_varticle.lastreplyuser = lastreplyuser;
            return cms_varticle;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cateid
        {
            get
            {
                return _cateid;
            }
            set
            {
                OncateidChanging(value);
                ReportPropertyChanging("cateid");
                _cateid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cateid");
                OncateidChanged();
            }
        }
        private global::System.Int32 _cateid;
        partial void OncateidChanging(global::System.Int32 value);
        partial void OncateidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String catepath
        {
            get
            {
                return _catepath;
            }
            set
            {
                OncatepathChanging(value);
                ReportPropertyChanging("catepath");
                _catepath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("catepath");
                OncatepathChanged();
            }
        }
        private global::System.String _catepath;
        partial void OncatepathChanging(global::System.String value);
        partial void OncatepathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 articleid
        {
            get
            {
                return _articleid;
            }
            set
            {
                OnarticleidChanging(value);
                ReportPropertyChanging("articleid");
                _articleid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("articleid");
                OnarticleidChanged();
            }
        }
        private global::System.Int32 _articleid;
        partial void OnarticleidChanging(global::System.Int32 value);
        partial void OnarticleidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentid
        {
            get
            {
                return _parentid;
            }
            set
            {
                OnparentidChanging(value);
                ReportPropertyChanging("parentid");
                _parentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentid");
                OnparentidChanged();
            }
        }
        private global::System.Int32 _parentid;
        partial void OnparentidChanging(global::System.Int32 value);
        partial void OnparentidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 layer
        {
            get
            {
                return _layer;
            }
            set
            {
                OnlayerChanging(value);
                ReportPropertyChanging("layer");
                _layer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("layer");
                OnlayerChanged();
            }
        }
        private global::System.Int32 _layer;
        partial void OnlayerChanging(global::System.Int32 value);
        partial void OnlayerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 subcount
        {
            get
            {
                return _subcount;
            }
            set
            {
                OnsubcountChanging(value);
                ReportPropertyChanging("subcount");
                _subcount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("subcount");
                OnsubcountChanged();
            }
        }
        private global::System.Int32 _subcount;
        partial void OnsubcountChanging(global::System.Int32 value);
        partial void OnsubcountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String catename
        {
            get
            {
                return _catename;
            }
            set
            {
                OncatenameChanging(value);
                ReportPropertyChanging("catename");
                _catename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("catename");
                OncatenameChanged();
            }
        }
        private global::System.String _catename;
        partial void OncatenameChanging(global::System.String value);
        partial void OncatenameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private global::System.Int32 _userid;
        partial void OnuseridChanging(global::System.Int32 value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String summary
        {
            get
            {
                return _summary;
            }
            set
            {
                OnsummaryChanging(value);
                ReportPropertyChanging("summary");
                _summary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("summary");
                OnsummaryChanged();
            }
        }
        private global::System.String _summary;
        partial void OnsummaryChanging(global::System.String value);
        partial void OnsummaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 viewcount
        {
            get
            {
                return _viewcount;
            }
            set
            {
                OnviewcountChanging(value);
                ReportPropertyChanging("viewcount");
                _viewcount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viewcount");
                OnviewcountChanged();
            }
        }
        private global::System.Int32 _viewcount;
        partial void OnviewcountChanging(global::System.Int32 value);
        partial void OnviewcountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderid
        {
            get
            {
                return _orderid;
            }
            set
            {
                OnorderidChanging(value);
                ReportPropertyChanging("orderid");
                _orderid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderid");
                OnorderidChanged();
            }
        }
        private global::System.Int32 _orderid;
        partial void OnorderidChanging(global::System.Int32 value);
        partial void OnorderidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte replypermit
        {
            get
            {
                return _replypermit;
            }
            set
            {
                OnreplypermitChanging(value);
                ReportPropertyChanging("replypermit");
                _replypermit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("replypermit");
                OnreplypermitChanged();
            }
        }
        private global::System.Byte _replypermit;
        partial void OnreplypermitChanging(global::System.Byte value);
        partial void OnreplypermitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Byte _status;
        partial void OnstatusChanging(global::System.Byte value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ip
        {
            get
            {
                return _ip;
            }
            set
            {
                OnipChanging(value);
                ReportPropertyChanging("ip");
                _ip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ip");
                OnipChanged();
            }
        }
        private global::System.String _ip;
        partial void OnipChanging(global::System.String value);
        partial void OnipChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createdate
        {
            get
            {
                return _createdate;
            }
            set
            {
                OncreatedateChanging(value);
                ReportPropertyChanging("createdate");
                _createdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdate");
                OncreatedateChanged();
            }
        }
        private global::System.DateTime _createdate;
        partial void OncreatedateChanging(global::System.DateTime value);
        partial void OncreatedateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String seotitle
        {
            get
            {
                return _seotitle;
            }
            set
            {
                OnseotitleChanging(value);
                ReportPropertyChanging("seotitle");
                _seotitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("seotitle");
                OnseotitleChanged();
            }
        }
        private global::System.String _seotitle;
        partial void OnseotitleChanging(global::System.String value);
        partial void OnseotitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String seodescription
        {
            get
            {
                return _seodescription;
            }
            set
            {
                OnseodescriptionChanging(value);
                ReportPropertyChanging("seodescription");
                _seodescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("seodescription");
                OnseodescriptionChanged();
            }
        }
        private global::System.String _seodescription;
        partial void OnseodescriptionChanging(global::System.String value);
        partial void OnseodescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String seokeywords
        {
            get
            {
                return _seokeywords;
            }
            set
            {
                OnseokeywordsChanging(value);
                ReportPropertyChanging("seokeywords");
                _seokeywords = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("seokeywords");
                OnseokeywordsChanged();
            }
        }
        private global::System.String _seokeywords;
        partial void OnseokeywordsChanging(global::System.String value);
        partial void OnseokeywordsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String seometas
        {
            get
            {
                return _seometas;
            }
            set
            {
                OnseometasChanging(value);
                ReportPropertyChanging("seometas");
                _seometas = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("seometas");
                OnseometasChanged();
            }
        }
        private global::System.String _seometas;
        partial void OnseometasChanging(global::System.String value);
        partial void OnseometasChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 typeid
        {
            get
            {
                return _typeid;
            }
            set
            {
                OntypeidChanging(value);
                ReportPropertyChanging("typeid");
                _typeid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("typeid");
                OntypeidChanged();
            }
        }
        private global::System.Int32 _typeid;
        partial void OntypeidChanging(global::System.Int32 value);
        partial void OntypeidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 favor
        {
            get
            {
                return _favor;
            }
            set
            {
                OnfavorChanging(value);
                ReportPropertyChanging("favor");
                _favor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("favor");
                OnfavorChanged();
            }
        }
        private global::System.Int32 _favor;
        partial void OnfavorChanging(global::System.Int32 value);
        partial void OnfavorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 against
        {
            get
            {
                return _against;
            }
            set
            {
                OnagainstChanging(value);
                ReportPropertyChanging("against");
                _against = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("against");
                OnagainstChanged();
            }
        }
        private global::System.Int32 _against;
        partial void OnagainstChanging(global::System.Int32 value);
        partial void OnagainstChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rename
        {
            get
            {
                return _rename;
            }
            set
            {
                OnrenameChanging(value);
                ReportPropertyChanging("rename");
                _rename = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rename");
                OnrenameChanged();
            }
        }
        private global::System.String _rename;
        partial void OnrenameChanging(global::System.String value);
        partial void OnrenameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tags
        {
            get
            {
                return _tags;
            }
            set
            {
                OntagsChanging(value);
                ReportPropertyChanging("tags");
                _tags = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tags");
                OntagsChanged();
            }
        }
        private global::System.String _tags;
        partial void OntagsChanging(global::System.String value);
        partial void OntagsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte iscommend
        {
            get
            {
                return _iscommend;
            }
            set
            {
                OniscommendChanging(value);
                ReportPropertyChanging("iscommend");
                _iscommend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iscommend");
                OniscommendChanged();
            }
        }
        private global::System.Byte _iscommend;
        partial void OniscommendChanging(global::System.Byte value);
        partial void OniscommendChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte istop
        {
            get
            {
                return _istop;
            }
            set
            {
                OnistopChanging(value);
                ReportPropertyChanging("istop");
                _istop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("istop");
                OnistopChanged();
            }
        }
        private global::System.Byte _istop;
        partial void OnistopChanging(global::System.Byte value);
        partial void OnistopChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime lastreplydate
        {
            get
            {
                return _lastreplydate;
            }
            set
            {
                OnlastreplydateChanging(value);
                ReportPropertyChanging("lastreplydate");
                _lastreplydate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastreplydate");
                OnlastreplydateChanged();
            }
        }
        private global::System.DateTime _lastreplydate;
        partial void OnlastreplydateChanging(global::System.DateTime value);
        partial void OnlastreplydateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastreplyuser
        {
            get
            {
                return _lastreplyuser;
            }
            set
            {
                OnlastreplyuserChanging(value);
                ReportPropertyChanging("lastreplyuser");
                _lastreplyuser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastreplyuser");
                OnlastreplyuserChanged();
            }
        }
        private global::System.String _lastreplyuser;
        partial void OnlastreplyuserChanging(global::System.String value);
        partial void OnlastreplyuserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();

        #endregion
    
    }

    #endregion
    
}
